### ISSUE TITLE
PHP Warning:  preg_match_all()

### ISSUE THREAD

**Issue by xbgmsharp** [nuovo/vCard-parser#1]
Hi,

On lines 92 and 93 it generate PHP warning.
      $vCardBeginCount = preg_match_all('{^BEGIN:VCARD}miS', $this -> RawData);
      $vCardEndCount = preg_match_all('{^END:VCARD}miS', $this -> RawData);

PHP Warning:  preg_match_all() expects at least 3 parameters, 2 given in vCard.php on line 92
PHP Warning:  preg_match_all() expects at least 3 parameters, 2 given in vCard.php on line 93

**Comment by xbgmsharp** [comment]
Here is my version of PHP.

$ php -v
PHP 5.3.3-7+squeeze8 with Suhosin-Patch (cli) (built: Feb 10 2012 14:12:26) 
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Suhosin v0.9.32.1, Copyright (c) 2007-2010, by SektionEins GmbH

**Comment by pilsetnieks** [comment]
Fixed - the third parameter was made optional in 5.4, that's why I didn't catch that.
