### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by xbgmsharp** [nuovo/vCard-parser#10]
PHP Parse error:  syntax error, unexpected T_VARIABLE in vCard.php on line 209
-                                               $ItemIndex = (int)str_ireplace('item', '' $TmpKey[0]);
-                                               $ItemIndex = (int)str_ireplace('item', '', $TmpKey[0]);

**Comment by pilsetnieks** [comment]
Sorry, don't know how I missed that - fixed.
