### ISSUE TITLE
Howto create new entry with type and sub element (eg: adr)

### ISSUE THREAD

**Issue by xbgmsharp** [nuovo/vCard-parser#3]
Hi,

I am able to create simple entry with type HOME for example:
$vCard -> tel('555-1111', 'Home');
$vCard -> tel('555-1234', 'Work');

But how to do the same for ADR. with type and subvalue like StreetAddress
I am unable to figure it out.
Shold not be like this:
$vCard -> adr('My Country', 'Work', 'StreetAddress');
$vCard -> adr('My Country', 'StreetAddress', 'Work' );

I try to pass it as an array but no luck
$vCard -> adr('My Country', array('StreetAddress', 'Work') );

Any ideas?

**Comment by xbgmsharp** [comment]
The same apply to add photo.

**Comment by xbgmsharp** [comment]
Any update?

**Comment by xbgmsharp** [comment]
Any update?

**Comment by pilsetnieks** [comment]
Check out write-test.php - there's an example now of how to add an address. It works but it seems that I have to rethink the way complex values are added because this may be somewhat cumbersome.

**Comment by phobos2077** [comment]
This doesn't actually answer the question. In write-test.php I can see only adding different parts of structured field (StreetAddress, Locality, etc.) but not the Type. Looks like structured fields need to be rewritten.
