### ISSUE TITLE
vCard.php Parse Error

### ISSUE THREAD

**Issue by xbgmsharp** [nuovo/vCard-parser#6]
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in include/vCard.php on line 552
The line is missing the closing ')'

$Parameters = array_map(function($Item))

**Comment by pilsetnieks** [comment]
Are you sure about this? What PHP version are you using? It may happen if you're using anything older than PHP 5.3 where anonymous functions became available.

**Comment by xbgmsharp** [comment]
Correct it does append using PHP 5.2.17.

**Comment by pilsetnieks** [comment]
Should be fixed in the latest version
