### ISSUE TITLE
problematic vcard from Apple Addressbook

### ISSUE THREAD

**Issue by xbgmsharp** [nuovo/vCard-parser#7]
When using the parser some field disapear more likely the 'itemX' and 'X-'.
Where the 'X-' does not have too much value the 'itemX' does have a usefull value.

BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//Address Book 6.1.2//EN
N:von Besser;Hans;;Dr.;
FN:Eppendorf Vertrieb Deutschland GmbH
ORG:Eppendorf Vertrieb Deutschland GmbH;Vertriebsspezialist Systeme
EMAIL;type=INTERNET;type=WORK;type=pref:vbesser.h@eppendorf.de
TEL;type=WORK;type=VOICE;type=pref:+49 931 28 67 51
TEL;type=CELL;type=VOICE:+49 171 230 05 95
item1.ADR;type=WORK;type=pref:;;Büro Würzburg\nOberer Kühlenberg 14;Würzburg;;97078;Germany
item1.X-ABADR:de
item2.URL;type=pref:www.eppendorf.de
item2.X-ABLabel:$!!$
X-ABShowAs:COMPANY
CATEGORIES:Personal Address Book
UID:bb332361-6c7e-4782-babd-d7d5a5f158f4
X-ABUID:75F1F559-5C43-4763-8BDE-E02A9FB9F937:ABPerson
END:VCARD

**Comment by xbgmsharp** [comment]
interesting reading 
http://www.w3.org/2002/12/cal/vcard-notes.html

**Comment by pilsetnieks** [comment]
This is the same as [Issue #9](https://github.com/nuovo/vCard-parser/issues/9) - and it has been solved, partly. Full support for Apple's Address Book extensions, however, will take a lot more work.
